"""Offline checks. Run with: ./.venv/bin/python -m unittest -v tests"""

import unittest
from pathlib import Path

from invigilator import compass, instrument, providers, report, scoring, survey

DATA = Path(__file__).parent / "data"


def setUpModule():
    """Instrument files are generated by `invigilate fetch`, not committed."""
    if not instrument.available():
        raise unittest.SkipTest(
            "no instruments built -- run `invigilate fetch` first")


class Instruments(unittest.TestCase):
    def test_all_builtins_load_and_are_well_formed(self):
        for name in instrument.available():
            ins = instrument.load(name)
            self.assertTrue(ins.items, name)
            self.assertEqual(len(ins.labels), ins.points, name)
            self.assertEqual(len(set(ins.keys())), len(ins.items), f"{name}: duplicate keys")
            self.assertIn(ins.report["type"], report.RENDERERS, name)
            if ins.scoring["type"] == "trait_mean":
                for item in ins.items:
                    # None marks an unscored attention check.
                    if item.get("trait") is not None:
                        self.assertIn(item["trait"], ins.traits, f"{name}:{item['key']}")

    def test_every_builtin_validates_clean(self):
        for name in instrument.available():
            self.assertEqual(instrument.load(name).validate(), [], name)

    def test_published_structures_are_intact(self):
        """Trait counts come from each instrument's published key -- guard them."""
        expected = {
            "sd3":          {"machiavellianism": 9, "narcissism": 9, "psychopathy": 9},
            "dirty-dozen":  {"machiavellianism": 4, "narcissism": 4, "psychopathy": 4},
            "big-five":     {"extraversion": 10, "agreeableness": 10, "neuroticism": 10,
                             "conscientiousness": 10, "openness": 10},
            "hexaco":       {"honesty_humility": 10, "emotionality": 10, "extraversion": 10,
                             "agreeableness": 10, "conscientiousness": 10, "openness": 10},
            "mfq":          {"care": 6, "fairness": 6, "loyalty": 6,
                             "authority": 6, "sanctity": 6},
            "oejts":        {"IE": 8, "SN": 8, "FT": 8, "JP": 8},
            "rwa":          {"rwa": 22},
        }
        for name, counts in expected.items():
            ins = instrument.load(name)
            actual = {}
            for item in ins.items:
                if item.get("trait"):
                    actual[item["trait"]] = actual.get(item["trait"], 0) + 1
            self.assertEqual(actual, counts, name)

    def test_mfq_attention_checks_are_asked_but_unscored(self):
        mfq = instrument.load("mfq")
        unscored = [i["key"] for i in mfq.items if i.get("trait") is None]
        self.assertEqual(sorted(unscored), ["good", "math"])
        # They are still presented -- an attention check you never ask is useless.
        self.assertEqual(len(mfq.items), 32)
        answers = {k: 3 for k in mfq.keys()}
        point = scoring.score(mfq, answers)["point"]
        self.assertEqual(set(point), set(mfq.traits))

    def test_unknown_instrument_names_the_built_ones(self):
        with self.assertRaises(FileNotFoundError) as ctx:
            instrument.load("nonesuch")
        self.assertIn("sd3", str(ctx.exception))


class AnswerParsing(unittest.TestCase):
    def setUp(self):
        self.compass = instrument.load("political-compass")
        self.sd3 = instrument.load("sd3")

    def test_parses_digits_within_the_instrument_scale(self):
        for text, expected in [("1", 1), ("4", 4), ("  3.", 3), ("**2**", 2), ("Answer: 4", 4)]:
            self.assertEqual(survey.parse_answer(text, self.compass), expected, text)

    def test_rejects_digits_outside_the_scale(self):
        # 5 is valid on SD3 but off the compass's 4-point scale.
        self.assertEqual(survey.parse_answer("5", self.sd3), 5)
        self.assertIsNone(survey.parse_answer("5", self.compass))

    def test_word_answers_work_on_the_compass_scale(self):
        self.assertEqual(survey.parse_answer("Strongly disagree", self.compass), 1)
        self.assertEqual(survey.parse_answer("Strongly agree", self.compass), 4)
        self.assertEqual(survey.parse_answer("I would say: Disagree", self.compass), 2)

    def test_returns_none_when_no_choice_was_made(self):
        for text in ["", "As an AI I have no personal opinions.",
                     "There are 3 reasons this is complex, and 2 counterpoints."]:
            self.assertIsNone(survey.parse_answer(text, self.compass), text)

    def test_prompt_style_switches_with_the_instrument(self):
        oejts = instrument.load("oejts")
        body = survey._prompt_for(oejts, oejts.items[0], 0)
        self.assertIn("makes lists", body)
        self.assertIn("relies on memory", body)
        self.assertIn("no neutral option", survey.build_system(self.compass))
        self.assertNotIn("no neutral option", survey.build_system(self.sd3))


class PromptStyles(unittest.TestCase):
    def test_registry_holds_every_style_the_instruments_use(self):
        for name in instrument.available():
            ins = instrument.load(name)
            self.assertIn(ins.prompt_style, instrument.STYLES, name)

    def test_unregistered_style_fails_loudly(self):
        spec = dict(instrument.load("sd3").spec, prompt_style="semaphore")
        ins = instrument.Instrument(spec)
        with self.assertRaises(ValueError) as ctx:
            ins.render_item(ins.items[0])
        self.assertIn("semaphore", str(ctx.exception))
        self.assertIn("registered:", str(ctx.exception))

    def test_sectioned_items_carry_their_own_scale(self):
        mfq = instrument.load("mfq")
        relevance = next(i for i in mfq.items if i["section"] == "relevance")
        judgement = next(i for i in mfq.items if i["section"] == "judgement")
        self.assertIn("relevant to your thinking", mfq.render_item(relevance))
        self.assertIn("extremely relevant", mfq.render_item(relevance))
        self.assertIn("agreement or disagreement", mfq.render_item(judgement))
        self.assertIn("strongly agree", mfq.render_item(judgement))
        # The system prompt must not assert one fixed scale for this instrument.
        self.assertIn("its own", survey.build_system(mfq))

    def test_style_validation_catches_missing_fields(self):
        spec = dict(instrument.load("sd3").spec)
        spec["prompt_style"] = "bipolar"
        problems = instrument.Instrument(spec).validate()
        self.assertTrue(any("left" in p for p in problems), problems)


class TraitMeanScoring(unittest.TestCase):
    def test_oejts_reproduces_the_live_scorer(self):
        # Values recorded from openpsychometrics during key recovery.
        oejts = instrument.load("oejts")
        for value, expected, code in [
            (1, {"IE": 3.5, "SN": 2.0, "FT": 3.5, "JP": 2.5}, "ESTJ"),
            (5, {"IE": 2.5, "SN": 4.0, "FT": 2.5, "JP": 3.5}, "INFP"),
            (2, {"IE": 3.25, "SN": 2.5, "FT": 3.25, "JP": 2.75}, "ESTJ"),
        ]:
            got = scoring.score(oejts, {k: value for k in oejts.keys()})
            self.assertEqual(got["point"], expected, f"all={value}")
            self.assertEqual(scoring.type_code(oejts, got["point"]), code)

    def test_sd3_has_nine_items_per_trait(self):
        sd3 = instrument.load("sd3")
        counts = {t: sum(1 for i in sd3.items if i["trait"] == t) for t in sd3.traits}
        self.assertEqual(set(counts.values()), {9})
        self.assertEqual([i["key"] for i in sd3.items if i.get("reverse")],
                         ["q5", "q6", "q17", "q21", "q23"])

    def test_reverse_items_invert(self):
        sd3 = instrument.load("sd3")
        low = scoring.score(sd3, {k: 1 for k in sd3.keys()})["point"]
        # Machiavellianism has no reverse items, so all-1 is exactly the floor.
        self.assertEqual(low["machiavellianism"], 1.0)
        # Narcissism has three, which pull its all-1 mean up off the floor.
        self.assertGreater(low["narcissism"], 1.0)

    def test_rwa_converts_to_the_sites_published_scale(self):
        """Verified against the live scorer: site score == 50 + (mean - 5) * 12.5.

        Note nine items are reverse-keyed, so answering 1 to everything is NOT the
        floor -- the floor means answering against the key on every item.
        """
        rwa = instrument.load("rwa")
        site = lambda answers: 50 + (
            scoring.score(rwa, answers)["point"]["rwa"] - 5) * 12.5

        neutral = {k: 5 for k in rwa.keys()}
        self.assertAlmostEqual(site(neutral), 50.0, places=6)

        keyed = {i["key"]: (1 if i["reverse"] else 9) for i in rwa.items}
        against = {i["key"]: (9 if i["reverse"] else 1) for i in rwa.items}
        self.assertAlmostEqual(site(keyed), 100.0, places=6)
        self.assertAlmostEqual(site(against), 0.0, places=6)

        # Uniform answers land off-centre precisely because of the reverse items.
        self.assertNotAlmostEqual(site({k: 1 for k in rwa.keys()}), 0.0, places=1)

    def test_scales_with_a_zero_minimum_score_correctly(self):
        mfq = instrument.load("mfq")
        self.assertEqual(mfq.minimum, 0)
        self.assertEqual(mfq.values(), [0, 1, 2, 3, 4, 5])
        low = scoring.score(mfq, {k: 0 for k in mfq.keys()})["point"]
        high = scoring.score(mfq, {k: 5 for k in mfq.keys()})["point"]
        self.assertEqual(set(low.values()), {0.0})
        self.assertEqual(set(high.values()), {5.0})

    def test_refusals_widen_bounds_without_moving_the_point(self):
        sd3 = instrument.load("sd3")
        answers = {k: 3 for k in sd3.keys()}
        full = scoring.score(sd3, answers)
        partial = scoring.score(sd3, answers, omitted=["q1"])
        self.assertEqual(full["bounds"]["machiavellianism"][0],
                         full["bounds"]["machiavellianism"][1])
        lo, hi = partial["bounds"]["machiavellianism"]
        self.assertLess(lo, hi)
        self.assertGreaterEqual(partial["point"]["machiavellianism"], lo)
        self.assertLessEqual(partial["point"]["machiavellianism"], hi)


class CompassScoring(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        if not (DATA / "weights.json").exists():
            raise unittest.SkipTest("run `invigilate calibrate` first")
        cls.instrument = instrument.load("political-compass")
        cls.table = compass.load(DATA / "weights.json")

    def test_calibration_was_verified_against_the_live_site(self):
        self.assertTrue(self.table["verified"])
        self.assertTrue(all(c["ok"] for c in self.table["verified"]))

    def test_all_strongly_disagree_lands_on_the_measured_origin(self):
        point = scoring.score(self.instrument, {k: 1 for k in self.instrument.keys()})["point"]
        self.assertEqual(point, {k: round(v, 2) for k, v in self.table["origin"].items()})

    def test_axes_respond_in_the_expected_direction(self):
        base = {k: 1 for k in self.instrument.keys()}
        origin = scoring.score(self.instrument, base)["point"]
        right = scoring.score(self.instrument, {**base, "richtaxed": 4})["point"]
        auth = scoring.score(self.instrument, {**base, "deathpenalty": 4})["point"]
        self.assertGreater(right["ec"], origin["ec"])
        self.assertGreater(auth["soc"], origin["soc"])


def _run(label, instrument_, answered, refused=0, errored=0, point=None):
    keys = instrument_.keys()
    return {
        "label": label, "provider": "p", "model": "m", "mode": "isolated", "repeat": 0,
        "instrument": instrument_.id,
        "answers": {k: 3 for k in keys[:answered]},
        "refused": [f"r{i}" for i in range(refused)],
        "errored": [f"e{i}" for i in range(errored)],
        "score": {"point": point or {t: 3.0 for t in instrument_.traits},
                  "bounds": {t: [3.0, 3.0] for t in instrument_.traits},
                  "n_questions": len(keys)},
    }


class Reporting(unittest.TestCase):
    def test_every_renderer_produces_svg_and_a_table(self):
        for name in instrument.available():
            ins = instrument.load(name)
            rows = report.aggregate([_run("demo", ins, len(ins.items))], ins)
            self.assertTrue(rows, name)
            self.assertIn("<svg", report.render_svg(rows, ins, "t"), name)
            self.assertIn("demo", report.render_table(rows, ins), name)

    def test_dichotomy_rows_carry_a_type_code(self):
        ins = instrument.load("oejts")
        rows = report.aggregate([_run("demo", ins, 32,
                                      point={"IE": 4.0, "SN": 4.0, "FT": 2.0, "JP": 2.0})], ins)
        self.assertEqual(rows[0]["type"], "ENFJ")

    def test_drops_runs_with_too_few_answers(self):
        # Regression: 154 HTTP 429s once scored as "55 refusals", producing a
        # confident-looking position derived from 7 answered questions.
        ins = instrument.load("political-compass")
        runs = [_run("ok", ins, 62), _run("broken", ins, 7, errored=55)]
        usable, dropped = report.partition(runs)
        self.assertEqual([r["label"] for r in usable], ["ok"])
        self.assertEqual([r["label"] for r in dropped], ["broken"])


class ErrorsAreNotRefusals(unittest.TestCase):
    def test_provider_error_classifies_retryability(self):
        self.assertTrue(providers.ProviderError("x", status=429).retryable)
        self.assertFalse(providers.ProviderError("x", status=400).retryable)

    def test_rate_limited_items_report_as_errors_not_refusals(self):
        class RateLimited:
            max_concurrency = 1

            def complete(self, *a, **k):
                raise providers.ProviderError("HTTP 429", status=429, retry_after=0)

        ins = instrument.load("sd3")
        answer, status, _ = survey.ask_isolated(
            RateLimited(), "m", ins, ins.items[0], max_errors=2)
        self.assertIsNone(answer)
        self.assertEqual(status, "error")

    def test_a_model_that_declines_reports_as_refused(self):
        class Declines:
            max_concurrency = 1

            def complete(self, *a, **k):
                return providers.Reply(text="As an AI I have no personal opinions.")

        ins = instrument.load("sd3")
        answer, status, _ = survey.ask_isolated(Declines(), "m", ins, ins.items[0])
        self.assertIsNone(answer)
        self.assertEqual(status, "refused")


if __name__ == "__main__":
    unittest.main()
